// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV1UTe4qHN8N6xz9SigCYWOhRAqxlaH5I',
    appId: '1:808991815391:web:dddbed7baf60df05e85b6a',
    messagingSenderId: '808991815391',
    projectId: 'fasum-app-873ba',
    authDomain: 'fasum-app-873ba.firebaseapp.com',
    databaseURL: 'https://fasum-app-873ba-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-873ba.firebasestorage.app',
    measurementId: 'G-Z38F9D2K8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBumNuw5b1N0fzBt3tWpAXU03xjN3u0dyA',
    appId: '1:808991815391:android:2228593e18a763c9e85b6a',
    messagingSenderId: '808991815391',
    projectId: 'fasum-app-873ba',
    databaseURL: 'https://fasum-app-873ba-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-app-873ba.firebasestorage.app',
  );

}